export const DEFAULT_BRANCH_ORDER: string[] = [
  'Area of Law',
  'Service',
  'Objectives',
  'Industry and Market',
  'Actor / Player',
  'Forums and Venues',
  'Governmental Body',
  'Document / Artifact',
  'Legal Entity',
  'Event',
  'Location',
  'Engagement Attributes',
  'Asset Type',
  'Legal Authorities',
  'Legal Use Cases',
  'Status',
  'Communication Modality',
  'Financial Concepts and Metrics',
  'Currency',
  'Matter Narrative',
  'Data Format',
  'Language',
  'System Identifiers',
];
